spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: railway

  mail:
    host: smtp.gmail.com
    username: Jojololamartins686@gmail.com
    password: svzmvfoipwikhzkz
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: smtp.gmail.com
          auth: true
          starttls:
            enable: true
            required: true

  sql:
    init:
      mode: always

JWT_SECRET: ${SECRET_JWT_SECRET}

#mail:
#  api:
#    key: ${KEY_MAIL_SECRET_KEY}
#sendinblue:
#  mail:
#    url: https://api.brevo.com/v3/emailCampaigns

cloudinary:
  cloud:
    name: martins-o
  api:
    secret: rco0un61BRlpULBBUzlitm0aWhU
    key: 432922932255442

AES_ALGORITHM: ${ALGORITHM:AES}
ENCRYPTION_KEY : ${KEY:my2243VeryLOnd2343EncryptionKey2}