spring:
  datasource:
    url: jdbc:mysql://localhost:3306/furnitureDB
    username: root
    password: 08146587069Gg@

mail:
  api:
    key: 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
sendinblue:
  mail:
    url: https://api.brevo.com/v3/emailCampaigns

cloudinary:
  cloud:
    name: martins-o
  api:
    secret: rco0un61BRlpULBBUzlitm0aWhU
    key: 432922932255442

AES_ALGORITHM: ${ALGORITHM:AES}
ENCRYPTION_KEY : ${KEY:my2243VeryLOnd2343EncryptionKey2}

#jwt:
#  secret:
#    key: D8FCF71D41352CD49FDD2762BEB69
#security:
#  constants:
#    jwt-secret: D8FCF71D41352CD49FDD2762BEB69
#    jwt-exp-time: 60