spring:
  datasource:
    url: jdbc:mysql://localhost:3306/furnitureDB
    username: root
    password: 08146587069Gg@

  mail:
    host: smtp.gmail.com
    username: Jojololamartins686@gmail.com
    password: svzmvfoipwikhzkz
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 465
          auth: true
          starttls:
            enable: true
            required: true

mail:
  api:
    key: ${MAIL_SECRET_KEY}
sendinblue:
  mail:
    url: https://api.brevo.com/v3/emailCampaigns

cloudinary:
  cloud:
    name: martins-o
  api:
    secret: rco0un61BRlpULBBUzlitm0aWhU
    key: 432922932255442

AES_ALGORITHM: ${ALGORITHM:AES}
ENCRYPTION_KEY : ${KEY:my2243VeryLOnd2343EncryptionKey2}



#jwt:
#  secret:
#    key: D8FCF71D41352CD49FDD2762BEB69
#security:
#  constants:
JWT_SECRET: ${SECRET:my32characterultrasecureandultraLongsecret124632432}
#    jwt-exp-time: 60